# noinspection PyDictCreation
class Costs:
    card_list = {}
    card_list["R2 Astromech"] = 1
    card_list["R4-D6"] = 1
    card_list["R2-D6"] = 1
    card_list["R5 Astromech"] = 1
    card_list["R5-X3"] = 1
    card_list["BB-8"] = 2
    card_list["R3-A2"] = 2
    card_list["R5-K6"] = 2
    card_list["R7 Astromech"] = 2
    card_list["Targeting Astromech"] = 2
    card_list["R2-F2"] = 3
    card_list["R5-D8"] = 3
    card_list["R5-P9"] = 3
    card_list["R7-T1"] = 3
    card_list["R2-D2"] = 4

    card_list["Ion Bombs"] = 2
    card_list["Seismic Charges"] = 2
    card_list["Proximity Mines"] = 3
    card_list["Cluster Mines"] = 4
    card_list["Conner Net"] = 4
    card_list["Proton Bombs"] = 5

    card_list["Tractor Beam"] = 1
    card_list["Flechette Cannon"] = 2
    card_list["Ion Cannon"] = 3
    card_list["Mangler Cannon"] = 4
    card_list["AutoBlaster"] = 5
    card_list["Heavy Laser Cannon"] = 7

    card_list["Docking Clamps"] = 0
    card_list["Expanded Cargo Hold"] = 1
    card_list["Broadcast Array"] = 2
    card_list["Backup Shield Generator"] = 3
    card_list["EM Emitter"] = 3
    card_list["Engine Booster"] = 3
    card_list["Cluster Bombs"] = 4
    card_list["Comms Booster"] = 4
    card_list["Frequency Jammer"] = 4
    card_list["Ionization Reactor"] = 4
    card_list["Shield Projector"] = 4
    card_list["Tibanna Gas Supplies"] = 4
    card_list["Slicer Tools"] = 7

    card_list["Chopper"] = 0
    card_list["Bombardier"] = 1
    card_list["Greedo"] = 1
    card_list["Hera Syndulla"] = 1
    card_list["Intelligence Agent"] = 1
    card_list["Nien Nunb"] = 1
    card_list["Shield Technician"] = 1
    card_list["Zeb Orrelios"] = 1
    card_list["Admiral Ozzel"] = 2
    card_list["Agent Kallus"] = 2
    card_list["Bossk"] = 2
    card_list["Captain Needa"] = 2
    card_list["Dash Rendar"] = 2
    card_list["Han Solo"] = 2
    card_list["Jan Ors"] = 2
    card_list["Leebo"] = 2
    card_list["Mercenary Copilot"] = 2
    card_list["Moff Jerjerrod"] = 2
    card_list["Outlaw Tech"] = 2
    card_list["Sabine Wren"] = 2
    card_list["Saboteur"] = 2
    card_list["Tactician"] = 2
    card_list["WED-15 Repair Droid"] = 2
    card_list["C-3PO"] = 3
    card_list["Carlist Rieekan"] = 3
    card_list["Construction Droid"] = 3
    card_list["Darth Vader"] = 3
    card_list["Ezra Bridger"] = 3
    card_list["Fleet Officer"] = 3
    card_list["K4 Security Droid"] = 3
    card_list["Kanan Jarrus"] = 3
    card_list["Kyle Katarn"] = 3
    card_list["Lando Calrissian"] = 3
    card_list["Mara Jade"] = 3
    card_list["Navigator"] = 3
    card_list["Rear Admiral Chiraneau"] = 3
    card_list["Rebel Captive"] = 3
    card_list["Recon Specialist"] = 3
    card_list["Weapons Engineer"] = 3
    card_list["Chewbacca"] = 4
    card_list["Flight Instructor"] = 4
    card_list["Leia Organa"] = 4
    card_list["R2-D2 (Crew)"] = 4
    card_list["Targeting Coordinator"] = 4
    card_list["Ysanne Isard"] = 4
    card_list["Gunner"] = 5
    card_list["Grand Moff Tarkin"] = 6
    card_list["Jan Dodonna"] = 6
    card_list["Raymus Antilles"] = 6
    card_list["Toryn Farr"] = 6
    card_list["Luke Skywalker"] = 7
    card_list["Emperor Palpatine"] = 8

    card_list["Adrenaline Rush"] = 1
    card_list["Calculation"] = 1
    card_list["Cool Hand"] = 1
    card_list["Crack Shot"] = 1
    card_list["Deadeye"] = 1
    card_list["Determination"] = 1
    card_list["Draw Their Fire"] = 1
    card_list["Lightning Reflexes"] = 1
    card_list["Veteran Instincts"] = 1
    card_list["Wired"] = 1
    card_list["Bodyguard"] = 2
    card_list["Decoy"] = 2
    card_list["Elusiveness"] = 2
    card_list["Expert Handling"] = 2
    card_list["Intimidation"] = 2
    card_list["Juke"] = 2
    card_list["Lone Wolf"] = 2
    card_list["Squad Leader"] = 2
    card_list["Stay On Target"] = 2
    card_list["Stay on Target"] = 2
    card_list["Swarm Tactics"] = 2
    card_list["Wingman"] = 2
    card_list["Daredevil"] = 3
    card_list["Marksmanship"] = 3
    card_list["Outmaneuver"] = 3
    card_list["Predator"] = 3
    card_list["Push the Limit"] = 3
    card_list["Ruthlessness"] = 3
    card_list["Expose"] = 4
    card_list["Opportunist"] = 4

    card_list["Dual Laser Turret"] = 5
    card_list["Ion Cannon Battery"] = 6
    card_list["Quad Laser Cannons"] = 6
    card_list["Single Turbolasers"] = 8

    card_list["Inertial Dampeners"] = 1
    card_list["Cloaking Device"] = 2
    card_list["Dead Man's Switch"] = 2
    card_list["Dead Mans Switch"] = 2
    card_list["Feedback Array"] = 2
    card_list["Glitterstim"] = 2
    card_list["Hot Shot Blaster"] = 3

    card_list["Chardaan Refit"] = -2
    card_list["XX-23 S-Thread Tracers"] = 1
    card_list["Advanced Homing Missiles"] = 3
    card_list["Adv. Homing Missiles"] = 3
    card_list["Ion Pulse Missiles"] = 3
    card_list["Proton Rockets"] = 3
    card_list["Cluster Missiles"] = 4
    card_list["Concussion Missiles"] = 4
    card_list["Assault Missiles"] = 5
    card_list["Homing Missiles"] = 5

    card_list["Guidance Chips"] = 0
    card_list["Integrated Astromech"] = 0
    card_list["Long-Range Scanners"] = 0
    card_list["B-Wing/E2"] = 1
    card_list["b-wing/E2"] = 1
    card_list["bwing/E2"] = 1
    card_list["Maneuvering Fins"] = 1
    card_list["Munitions Failsafe"] = 1
    card_list["Tactical Jammer"] = 1
    card_list["Twin Ion Engine Mk. II"] = 1
    card_list["Advanced SLAM"] = 2
    card_list["Anti-Pursuit Lasers"] = 2
    card_list["Autothrusters"] = 2
    card_list["Ion Projector"] = 2
    card_list["Stygium Particle Accelerator"] = 2
    card_list["Targeting Computer"] = 2
    card_list["Countermeasures"] = 3
    card_list["Experimental Interface"] = 3
    card_list["Hull Upgrade"] = 3
    card_list["Stealth Device"] = 3
    card_list["Advanced Cloaking Device"] = 4
    card_list["Engine Upgrade"] = 4
    card_list["Shield Upgrade"] = 4
    card_list["Automated Protocols"] = 5
    card_list["Optimized Generators"] = 5
    card_list["Ordnance Tubes"] = 5
    card_list["Combat Retrofit"] = 10

    card_list["Academy Pilot"] = 12
    card_list["Bandit Squadron Pilot"] = 12
    card_list["Binayre Pirate"] = 12
    card_list["Black Sun Soldier"] = 13
    card_list["Obsidian Squadron Pilot"] = 13
    card_list["Tala Squadron Pilot"] = 13
    card_list["Black Squadron Pilot"] = 14
    card_list["Cartel Spacer"] = 14
    card_list["Chaser"] = 14
    card_list["Wampa"] = 14
    card_list["Epsilon Squadron Pilot"] = 15
    card_list["KaaTo Leeachos"] = 15
    card_list["Night Beast"] = 15
    card_list["Winged Gundark"] = 15
    card_list["Youngster"] = 15
    card_list["Backstabber"] = 16
    card_list["Dark Curse"] = 16
    card_list["Rebel Operative"] = 16
    card_list["Scimitar Squadron Pilot"] = 16
    card_list["Sienar Test Pilot"] = 16
    card_list["Spice Runner"] = 16
    card_list["Zeta Squadron Pilot"] = 16
    card_list["Epsilon Ace"] = 17
    card_list["Lt. Blount"] = 17
    card_list["Mauler Mithel"] = 17
    card_list["NDru Suhlak"] = 17
    card_list["Omega Squadron Pilot"] = 17
    card_list["Prototype Pilot"] = 17
    card_list["Scourge"] = 17
    card_list["Tansarii Point Veteran"] = 17
    card_list["Alpha Squadron Pilot"] = 18
    card_list["Gamma Squadron Pilot"] = 18
    card_list["Gold Squadron Pilot"] = 18
    card_list["Howlrunner"] = 18
    card_list["Laetin Ashera"] = 18
    card_list["Syndicate Thug"] = 18
    card_list["Zeb Orrelios"] = 18
    card_list["Zeta Ace"] = 18
    card_list["Airen Cracken"] = 19
    card_list["Epsilon Leader"] = 19
    card_list["Gamma Squadron Veteran"] = 19
    card_list["Green Squadron Pilot"] = 19
    card_list["Roark Garnet"] = 19
    card_list["Torkil Mux"] = 19
    card_list["Avenger Squadron Pilot"] = 20
    card_list["Cartel Marauder"] = 20
    card_list["Ezra Bridger"] = 20
    card_list["Gray Squadron Pilot"] = 20
    card_list["Hired Gun"] = 20
    card_list["Omega Ace"] = 20
    card_list["Palob Godalhi"] = 20
    card_list["Serissu"] = 20
    card_list["Zeta Leader"] = 20
    card_list["Cutlass Squadron Pilot"] = 21
    card_list["Kyle Katarn"] = 21
    card_list["Omega Leader"] = 21
    card_list["Omicron Group Pilot"] = 21
    card_list["Rookie Pilot"] = 21
    card_list["Saber Squadron Pilot"] = 21
    card_list["Sabine Wren"] = 21
    card_list["Tempest Squadron Pilot"] = 21
    card_list["Blue Squadron Pilot"] = 22
    card_list["Captain Jonus"] = 22
    card_list["Drea Renthal"] = 22
    card_list["Gemmer Sojan"] = 22
    card_list["Hera Syndulla (Attack Shuttle)"] = 22
    card_list["Royal Guard Pilot"] = 22
    card_list["Valen Rudor"] = 22
    card_list["Arvel Crynyd"] = 23
    card_list["Black Eight Squadron Pilot"] = 23
    card_list["Black Sun Ace"] = 23
    card_list["Dace Bonearm"] = 23
    card_list["Dutch Vander"] = 23
    card_list["Fel's Wrath"] = 23
    card_list["Lieutenant Colzet"] = 23
    card_list["Lieutenant Lorrir"] = 23
    card_list["Red Squadron Pilot"] = 23
    card_list["Storm Squadron Pilot"] = 23
    card_list["Tarn Mison"] = 23
    card_list["Warden Squadron Pilot"] = 23
    card_list["Blue Squadron Novice"] = 24
    card_list["Captain Yorr"] = 24
    card_list["Dagger Squadron Pilot"] = 24
    card_list["Jake Farrell"] = 24
    card_list["Kavil"] = 24
    card_list["Kir Kanos"] = 24
    card_list["Tetran Cowall"] = 24
    card_list["Tomax Bren"] = 24
    card_list["Biggs Darklighter"] = 25
    card_list["Black Sun Enforcer"] = 25
    card_list["Commander Alozen"] = 25
    card_list["Graz the Hunter"] = 25
    card_list["Guardian Squadron Pilot"] = 25
    card_list["Hobbie Klivian"] = 25
    card_list["Horton Salm"] = 25
    card_list["Jan Ors"] = 25
    card_list["Sigma Squadron Pilot"] = 25
    card_list["The Inquisitor"] = 25
    card_list["Turr Phennir"] = 25
    card_list["Carnor Jax"] = 26
    card_list["Colonel Jendon"] = 26
    card_list["Deathrain"] = 26
    card_list["Garven Dreis"] = 26
    card_list["Jek Porkins"] = 26
    card_list["Major Rhymer"] = 26
    card_list["Nera Dantels"] = 26
    card_list["Red Squadron Veteran"] = 26
    card_list["Tycho Celchu"] = 26
    card_list["Zertik Strom"] = 26
    card_list["Black Sun Vigo"] = 27
    card_list["Blue Ace"] = 27
    card_list["Captain Kagi"] = 27
    card_list["Knave Squadron Pilot"] = 27
    card_list["Maarek Stele"] = 27
    card_list["Outer Rim Smuggler"] = 27
    card_list["Redline"] = 27
    card_list["Shadow Squadron Pilot"] = 27
    card_list["Soontir Fel"] = 27
    card_list["Esege Tuketu"] = 28
    card_list["Ibtisam"] = 28
    card_list["Juno Eclipse"] = 28
    card_list["Luke Skywalker"] = 28
    card_list["Talonbane Cobra"] = 28
    card_list["Zuckuss"] = 28
    card_list["Blackmoon Squadron Pilot"] = 29
    card_list["Darth Vader"] = 29
    card_list["Keyan Farlander"] = 29
    card_list["Miranda Doni"] = 29
    card_list["Red Ace"] = 29
    card_list["Trandoshan Slaver"] = 29
    card_list["Wedge Antilles"] = 29
    card_list["Wes Janson"] = 29
    card_list["Delta Squadron Pilot"] = 30
    card_list["Echo"] = 30
    card_list["Ello Asty"] = 30
    card_list["GR-75 Medium Transport"] = 30
    card_list["Guri"] = 30
    card_list["Wild Space Fringer"] = 30
    card_list["Poe Dameron"] = 31
    card_list["Prince Xizor"] = 31
    card_list["Ten Numb"] = 31
    card_list["Eaden Vrill"] = 32
    card_list["Etahn A'Baht"] = 32
    card_list["Onyx Squadron Pilot"] = 32
    card_list["Whisper"] = 32
    card_list["Bounty Hunter"] = 33
    card_list["Dengar"] = 33
    card_list["Latts Razzi"] = 33
    card_list["Leebo"] = 34
    card_list["Moralo Eval"] = 34
    card_list["Bossk"] = 35
    card_list["Colonel Vessery"] = 35
    card_list["Corran Horn"] = 35
    card_list["Mandalorian Mercenary"] = 35
    card_list["Dash Rendar"] = 36
    card_list["Emon Azzameen"] = 36
    card_list["IG-88A"] = 36
    card_list["IG-88B"] = 36
    card_list["IG-88C"] = 36
    card_list["IG-88D"] = 36
    card_list["Krassis Trelix"] = 36
    card_list["Chopper"] = 37
    card_list["Rexler Brath"] = 37
    card_list["Kanan Jarrus"] = 38
    card_list["Kath Scarlet"] = 38
    card_list["Kath Scarlet (Scum)"] = 38
    card_list["Boba Fett"] = 39
    card_list["Boba Fett (Scum)"] = 39
    card_list["CR90 Corvette (Aft)"] = 40
    card_list["Gozanti-class Cruiser"] = 40
    card_list["Hera Syndulla"] = 40
    card_list["Patrol Leader"] = 40
    card_list["Captain Oicunn"] = 42
    card_list["Chewbacca"] = 42
    card_list["Commander Kenkirk"] = 44
    card_list["Lando Calrissian"] = 44
    card_list["Han Solo"] = 46
    card_list["Rear Admiral Chiraneau"] = 46
    card_list["CR90 Corvette (Fore)"] = 50
    card_list["Raider-class Corvette (Aft)"] = 50
    card_list["Raider-class Corvette (Fore)"] = 50
    card_list["4-LOM"] = 100
    card_list["Baron of ???"] = 100
    card_list["Contrac???"] = 100
    card_list["Count???"] = 100
    card_list["Dea???"] = 100
    card_list["Gand ???"] = 100
    card_list["Glaive Squa???"] = 100
    card_list["Lothal ???"] = 100
    card_list["Maarek Stele (TIE Defender)"] = 100
    card_list["Manaroo"] = 100
    card_list["Ruth???"] = 100
    card_list["Tel Trevura"] = 100

    card_list["Genius"] = 0
    card_list["Unhinged Astromech"] = 1
    card_list["R4 Agromech"] = 2
    card_list["Salvaged Astromech"] = 2
    card_list["R4-B11"] = 3

    card_list["Enhanced Scopes"] = 1
    card_list["Fire-Control System"] = 2
    card_list["Accuracy Corrector"] = 3
    card_list["Advanced Sensors"] = 3
    card_list["Reinforced Deflectors"] = 3
    card_list["Sensor Jammer"] = 4
    card_list["Advanced Targeting Computer"] = 5

    card_list["Engineering Team"] = 4
    card_list["Gunnery Team"] = 4
    card_list["Sensor Team"] = 4
    card_list["Ordnance Experts"] = 5

    card_list["Weapons Guidance"] = 2
    card_list["Comm Relay"] = 3

    card_list["TIE/x7"] = -2
    card_list["Andrasta"] = 0
    card_list["A-Wing Test Pilot"] = 0
    card_list["BTL-A4 Y-Wing"] = 0
    card_list["Ghost"] = 0
    card_list["IG-2000"] = 0
    card_list["Mist Hunter"] = 0
    card_list["Phantom"] = 0
    card_list["Royal Guard TIE"] = 0
    card_list["Slave 1"] = 0
    card_list["TIE/D"] = 0
    card_list["TIE Shuttle"] = 0
    card_list["TIE/x1"] = 0
    card_list["Millennium Falcon"] = 1
    card_list["TIE/v1"] = 1
    card_list["Virago"] = 1
    card_list["Assailer"] = 2
    card_list["Dauntless"] = 2
    card_list["Dutyfree"] = 2
    card_list["Heavy Scyk Interceptor (Cannon)"] = 2
    card_list["Heavy Scyk Interceptor (Missile)"] = 2
    card_list["Heavy Scyk Interceptor (Torpedo)"] = 2
    card_list["Jaina's Light"] = 2
    card_list["Vector"] = 2
    card_list["Impetuous"] = 3
    card_list["Moldy Crow"] = 3
    card_list["ST-321"] = 3
    card_list["Dodonna's Pride"] = 4
    card_list["Instigator"] = 4
    card_list["Quantum Storm"] = 4
    card_list["Requiem"] = 4
    card_list["Tantive IV"] = 4
    card_list["Bright Hope"] = 5
    card_list["Outrider"] = 5
    card_list["Hound's Tooth"] = 6
    card_list["Suppressor"] = 6
    card_list["Punishing One"] = 12

    card_list["Bomb Loadout"] = 0
    card_list["Extra Munitions"] = 2
    card_list["Flechette Torpedoes"] = 2
    card_list["Plasma Torpedoes"] = 3
    card_list["Proton Torpedoes"] = 4
    card_list["Advanced Proton Torpedoes"] = 6
    card_list["Ion Torpedoes"] = 5

    card_list["Autoblaster Turret"] = 2
    card_list["Dorsal Turret"] = 3
    card_list["Blaster Turret"] = 4
    card_list["Ion Cannon Turret"] = 5
    card_list["Twin Laser Turret"] = 6

